### PR TITLE
Hotfix/development mode (plus some vagrant documentation)

### PR DESCRIPTION
**Pull request by jeremiahsmall**
Since `'ZF\DevelopmentMode',` obviously must be included in `config/application.config.php` so that it can be run before a `config/development.config.php` has been deployed, this means that the application will always expect the module to exist. If you compose a project with `--no-dev`, if composer does not install the module, the application throws a fatal error from the module manager:

```
Fatal error: Uncaught exception 'Zend\ModuleManager\Exception\RuntimeException' with message 'Module (ZF\DevelopmentMode) could not be initialized.' in /vagrant/vendor/zendframework/zendframework/library/Zend/ModuleManager/ModuleManager.php on line 195
```

This PR also removes the `composer.lock` file, adds `.vagrant` to `.gitignore` and adds a helpful welcome message to the end of `Vagrantfile`.

### CODE REVIEW

**Comment by TomHAnderson** [comment]
:+1:

**Comment by jeremiahsmall** [comment]
#89 could be edited to point to develop. It points to master currently. If that's merged, I'll still suggest this be added, as it also has some additional housekeeping which is useful.

**Comment by ezimuel** [comment]
@jeremiahsmall yes, you right regarding the `zf-developmentmode`. I'm not sure about removing `composer.lock` from git. The `zf-apigility-skeleton` is an application rather than a library and I think it the .lock should be included. @weierophinney what do you think?

**Comment by jeremiahsmall** [comment]
Fwiw, we don't include it in the ZF2 Skeleton App. That actually makes me wonder: we *do* include composer.phar in that one. Should it be added here? I guess not, since it's a pain to keep it current that way.

**Comment by ezimuel** [comment]
@jeremiahsmall that's a good point. Personally, I think we should remove `composer.phar` from ZF2 Skeleton Application and add `composer.lock`, but this is questionable.

**Comment by ezimuel** [comment]
@jeremiahsmall I just spoke with @weierophinney and he agree with me, we should include `composer.lock` in Apigility and ZF2 skeleton app and remove `composer.pha`r. Can you include `composer.lock` again in this PR? Thanks!

**Comment by jeremiahsmall** [comment]
Would you like me to PR same thing on the main Skeleton App? (remove composer.phar and add composer.json)

**Comment by jeremiahsmall** [comment]
Maybe a good compromise would be to leave `composer.phar` in ZendSkeletonApplication, and also add it here, along with the same instructions in the README. Then also add the compser.lock file to ZendSkeletonApplication. This would at least make them the same. Then further discussion could be had regarding if the phar should be shipped.

**Comment by TomHAnderson** [comment]
I'm keeping track of these changes here: http://tomhanderson.blogspot.com/2015/06/guidelines-for-composer-based-skeleton.html

**Comment by ezimuel** [comment]
@jeremiahsmall Thanks!

**Pull request merged**
